# .github/release.yml
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - ":loudspeaker: semver: major"
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - ":loudspeaker: semver: minor"
        - "enhancement"
        - "feature"
        - feature
    - title: Optimizations ⏩
      labels:
        - "optimisation"
    - title: Clean code 👌
      labels: 
        - "cleanup"
        - "refactor"
    - title: Bugs fixed 💚
      labels:
        - "bug"
        - "bug: ftbs" 
        - "bug: fte"
    - title: Other Changes 
      labels:
        - "*"
