site:
  title: Benchmarking
  url: https://feelpp.github.io/benchmarking/
  start_page: benchmarking::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
ui:
  supplemental_files: ./docs/antora/supplemental-ui
  bundle:
    url: https://github.com/feelpp/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: public
antora:
  extensions:
  - '@antora/collector-extension'
asciidoc:
  extensions:
  - '@feelpp/asciidoctor-extensions'
