
= Reframe Report for gaya
:page-plotly: true
:page-jupyter: true
:page-tags: case
:description: Performance report for gaya on 2024-05-31T00:45:12+0200
:page-illustration: gaya.jpg
:author: Your Name
:revdate: 2024-05-31T00:45:12+0200

== Test Summary

* Total Tests: 8
* Failures: 0
* Testcases
** HeatToolboxTest %nbTask=128 %case=/home/u4/csmi/2023/pierre/gayaReframe/cases/case3-bench.cfg
** HeatToolboxTest %nbTask=64 %case=/home/u4/csmi/2023/pierre/gayaReframe/cases/case3-bench.cfg
** HeatToolboxTest %nbTask=32 %case=/home/u4/csmi/2023/pierre/gayaReframe/cases/case3-bench.cfg
** HeatToolboxTest %nbTask=16 %case=/home/u4/csmi/2023/pierre/gayaReframe/cases/case3-bench.cfg
** HeatToolboxTest %nbTask=8 %case=/home/u4/csmi/2023/pierre/gayaReframe/cases/case3-bench.cfg
** HeatToolboxTest %nbTask=4 %case=/home/u4/csmi/2023/pierre/gayaReframe/cases/case3-bench.cfg
** HeatToolboxTest %nbTask=2 %case=/home/u4/csmi/2023/pierre/gayaReframe/cases/case3-bench.cfg
** HeatToolboxTest %nbTask=1 %case=/home/u4/csmi/2023/pierre/gayaReframe/cases/case3-bench.cfg


[%dynamic%close,python]
----
from feelpp.benchmarking.reframe.report import Report
report=Report(file_path="docs/modules/gaya/pages/reports/gaya-20240530-1.json")
----

=== Performance by Simulation Steps 

[%dynamic%raw%open,python]
----
fig=report.plotPerformanceByStep()
fig.show()
----

=== Performance by Number of Tasks

[%dynamic%raw%open,python]
----
fig=report.plotPerformanceByTask()
fig.show()
----

=== Speedup of the simulation Steps

.Speedup
[%dynamic%raw%open,python]
----
print(report.speedup())
fig=report.plotSpeedup()
fig.show()
----

=== Speedup for partial performances
[%dynamic%close,python]
----
fig=report.plotPartialSpeedup('init')
fig.show()
----

[%dynamic%close,python]
----
fig=report.plotPartialSpeedup('solve')
fig.show()
----
