= Figures
:page-plotly: true
:page-jupyter: true

In order to generate reports, the _Feel++ benchmarking_ framework requires a figure description to specify what the website report page should contain.

These descriptions should be provided either with a specific JSON file with the structure containing uniquely

[source,json,subs=attributes]
----
{
    "plots":[]
}
----

Or by specifying the `plots` field on the benchmark configuration JSON file.

Each figure description should contain the following fields

[source,json]
----
{
    "title": "The figure title",
    "plot_types": [], //List of figure types
    "transformation": "", //Transformation type
    "variables":[], // List of variables to consider
    "names":[], //Respective labels for variables
    "yaxis":{},
    "xaxis":{},
    "color_axis":{}, //Default: performance variables
    "secondary_axis":{}
}
----

Figures will appear in the same order as they appear on the list.

Users can provide multiple plot_types in the same description field.

[NOTE]
====
Only performance variables specified under the `variables` list will be considered. If the list is empty, ALL variables inside the ReFrame report will be taken into account.
====

== Axis
Each axis (with the exception of the `yaxis`) take a `parameter` and a `label` field.
The `yaxis` will always contain the performance values, therefore only the `label` key should be specified.

The `parameter` field of each axis should correspond to either a single dimension parameter specified on the benchmark configuration.
In the case of subparameters, the syntax should be the following: `parameter.subparameter`.

By default, the color axis will contain the performance variables, but this can be customized.

== Transformations

The ReFrame report will be used to create a _Master DataFrame_, which will contain all performance variables and their respective values, as well as all parameters and environments.

To explain how transformation and plot types work, we can consider the following example.

[%dynamic%open%hide_code,python,subs=attributes]
----
import json
from feelpp.benchmarking.report.atomicReports.model import AtomicReportModel
with open("xref:attachment$data/reframe_report.json[]","r") as rfm_report:
    report = json.load(rfm_report)

model = AtomicReportModel(report["runs"])
model.master_df = model.master_df[model.master_df["performance_variable"].isin(["computation_time","communication_time"])].loc[:,["performance_variable","value","unit",	"testcase_time_run","environment","platform","nb_tasks.tasks","nb_tasks.exclusive_access","elements"]]
----


[%dynamic%open%hide_code,python]
----
model.master_df
----

We can see that this dataframe contains the parameters:
- environment
- platform
- nb_tasks.tasks
- nb_tasks.exclusive_access
- elements
- performance_variable

By having this common structure, we can make use of transformation strategies to manipulate values depending on the desired output.

Strategies will depend on the figure axis. All strategies will create a pivot dataframe that will contain the parameter specified as `color_axis` as columns, `xaxis` as first level index and `secondary_axis` as second level index. Values of the dataframe will always be the `values` of the master dataframe.

As an example, we will consider the following axis:
[source,json]
----
"xaxis":{
    "parameter":"nb_tasks.tasks",
    "label":"Number of tasks"
},
"yaxis":{
    "label":"Execution time (s)"
},
"secondary_axis":{
    "parameter":"elements",
    "label":"N"
},
"color_axis":{
    "parameter":"performance_variable",
    "label":"Performance variable"
}
----

Available strategies are:

- performance

This strategy should be seen as the "base" strategy. No transformation, other that a pivot, is done.
For the given example, it produces the following dataframe

[%dynamic%open%hide_code,python]
----
from feelpp.benchmarking.report.transformationFactory import TransformationStrategyFactory
from feelpp.benchmarking.reframe.config.configPlots import Plot
plot_config = Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "stacked_bar", "grouped_bar" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation","Comunication"],
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    }
})
strategy = TransformationStrategyFactory.create(plot_config)
df = strategy.calculate(model.master_df)
print(df)
----

- relative_performance

The relative performance strategy computes the proportion of the time that a a `color_axis` variable takes with regards of the total.

[%dynamic%open%hide_code,python]
----
from feelpp.benchmarking.report.transformationFactory import TransformationStrategyFactory
from feelpp.benchmarking.reframe.config.configPlots import Plot
plot_config = Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "stacked_bar", "grouped_bar" ],
    "transformation": "relative_performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation","Comunication"],
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    }
})
strategy = TransformationStrategyFactory.create(plot_config)
df = strategy.calculate(model.master_df)
print(df)
----

The sum along the column axis will always be equal to 1.

- speedup

The speedup strategy computes the speedup of the `color_axis` variables. The minimum of the `xaxis` values is taken as the base of the speedup.
For the example, this strategy will produce the following.

[%dynamic%open%hide_code,python]
----
from feelpp.benchmarking.report.transformationFactory import TransformationStrategyFactory
from feelpp.benchmarking.reframe.config.configPlots import Plot
plot_config = Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "stacked_bar", "grouped_bar" ],
    "transformation": "speedup",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation","Comunication"],
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    }
})
strategy = TransformationStrategyFactory.create(plot_config)
df = strategy.calculate(model.master_df)
print(df)
----

== Plot types

Considering the same example axis as above, the software can generate the following figures:

- `scatter`

[%dynamic%open%hide_code,python]
----
from feelpp.benchmarking.report.figures.figureFactory import FigureFactory
figures = FigureFactory.create(Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "scatter" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation","Comunication"],
    "color_axis":{
    "parameter":"performance_variable",
    "label":"Performance variable"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    },
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    }
}))
fig = figures[0].createFigure(model.master_df)
fig.show()
----

- `marked_scatter`

The marked scatter plot type supports from 2 to 4 dimensions. The symbol/marks axis will correspond to the `secondary_axis` parameter.
This plot type will behave as follows:

* If 1 or 2 dimensions are specified (x-axis and optionally color-axis), then this plot type will be equivalent to `scatter`.
* If 3 dimensions are specified (x-axis, color-axis and secondary-axis), then the `secondary_axis` will correspond to the symbol/marks axis.
* If 4 dimensions are specified (x-axis, color-axis, secondary-axis and one extra-axis), then the first element of the `extra_axes` list will correspond to the symbol/marks axis, and the `secondary_axis` will correspond to the slider of the returned animation.

[%dynamic%open%hide_code,python]
----

figures = FigureFactory.create(Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "marked_scatter" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation", "Communication"],
    "color_axis":{
        "parameter":"performance_variable",
        "label":"Performance variable"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    },
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    }
}))
for f in figures:
    fig = f.createFigure(model.master_df)
    fig.show()
----

- `stacked_bar`

[%dynamic%open%hide_code,python]
----
figures = FigureFactory.create(Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "stacked_bar" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation","Comunication"],
    "color_axis":{
    "parameter":"performance_variable",
    "label":"Performance variable"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    },
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    }
}))
fig = figures[0].createFigure(model.master_df)
fig.show()
----


- `grouped_bar`

[%dynamic%open%hide_code,python]
----
figures = FigureFactory.create(Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "grouped_bar" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation","Comunication"],
    "color_axis":{
    "parameter":"performance_variable",
    "label":"Performance variable"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    },
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    }
}))
fig = figures[0].createFigure(model.master_df)
fig.show()
----

- `heatmap`

For this case, we will consider the `elements` (N) as `color_axis` and `performance_variable` for secondary axis (slider).

[%dynamic%open%hide_code,python]
----
figures = FigureFactory.create(Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "heatmap" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation", "Communication"],
    "color_axis":{
        "parameter":"elements",
        "label":"N"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"performance_variable",
        "label":"Performance variable"
    },
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    }
}))
fig = figures[0].createFigure(model.master_df)
fig.show()
----

- `table`

[%dynamic%open%hide_code,python]
----
figures = FigureFactory.create(Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "table" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation","Comunication"],
    "color_axis":{
    "parameter":"performance_variable",
    "label":"Performance variable"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    },
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    }
}))
fig = figures[0].createFigure(model.master_df)
fig.show()
----

- `sunburst`

This figure considers the `color_axis` parameter as the outer-most ring.
Users can supply an `extra_axes` field, containing a list of additional parameters. Values for these parameters whill be shown on the rings that follow the `color_axis` ring, in the order they are provided.
The `secondary_axis` and `xaxis` parameter are present respectively on the inner-most and second inner-most rings.


[%dynamic%open%hide_code,python]
----
figures = FigureFactory.create(Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "sunburst" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation", "Communication"],
    "color_axis":{
        "parameter":"performance_variable",
        "label":"Performance variable"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    },
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    }
}))
fig = figures[0].createFigure(model.master_df)
fig.show()
----


- `parallelcoordinates`

Axes will be shown on the following order: `secondary_axis`, `xaxis`, all additional `extra_axes`, `color_axis`. The `yaxis` will be shown in the line color.

[%dynamic%open%hide_code,python]
----
figures = FigureFactory.create(Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "parallelcoordinates" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation", "Communication"],
    "color_axis":{
        "parameter":"performance_variable",
        "label":"Performance variable"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    },
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    },
    "extra_axes":[
        {
            "parameter":"dim3",
            "label":"Dim3"
        }
    ]
}))
for f in figures:
    fig = f.createFigure(model.master_df)
    fig.show()
----


=== 3D Plots

3D plots are also supported, and then can show up to 4 dimensions. At least 3 parameters must be provided (`xaxis`,`color_axis` and `secondary_axis` ).
Axes correspondance is as follows:

- x-axis of the 3D plot: `xaxis`
- y-axis of the 3D plot: `secondary_axis` if no extra axes are provided, else, the first element of the `extra_axes` list.
- z-axis of the 3D plot: `yaxis` (contains the measured values)
- color of the 3D traces: `color_axis`
- Slider: `secondary_axis` if extra axes are provided.

- `scatter3d`

[%dynamic%open%hide_code,python]
----
figures = FigureFactory.create(Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "scatter3d" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation", "Communication"],
    "color_axis":{
        "parameter":"performance_variable",
        "label":"Performance variable"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    },
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    }
}))
for f in figures:
    fig = f.createFigure(model.master_df)
    fig.show()
----

- `surface3d`

[%dynamic%open%hide_code,python]
----
figures = FigureFactory.create(Plot(**{
    "title": "Absolute performance",
    "plot_types": [ "surface3d" ],
    "transformation": "performance",
    "variables": [ "computation_time","communication_time" ],
    "names": ["Computation", "Communication"],
    "color_axis":{
        "parameter":"performance_variable",
        "label":"Performance variable"
    },
    "yaxis":{"label":"Execution time (s)"},
    "secondary_axis":{
        "parameter":"elements",
        "label":"N"
    },
    "xaxis":{
        "parameter":"nb_tasks.tasks",
        "label":"Number of tasks"
    }
}))
for f in figures:
    fig = f.createFigure(model.master_df)
    fig.show()
----


== Aggregations

Depending on the dashboard level that we are located at, it might be necessary to aggregate the data on the master dataframe.
For example, if we have all use cases, applications and machines on the dataframe, and we want to see how a certain use case performs on different machines, we can make use of the `aggregations` field to group the data accordingly.

[source,json]
----
"aggregations":[
    {"column":"date","agg":"max"},
    {"column":"applications","agg":"filter:my_app"},
    {"column":"use_cases","agg":"filter:my_use_case"},
    {"column":"performance_variable","agg":"sum"}
]
----

The previous example will first get only the latest benchmarks (by getting the maximum date), then it will filter the application and the use case to find applications and use cases that correspond to "my_app" and "my_use_case". And finally it will compute the sum of all performance variables for the remaining rows.

Users must provide a column and an aggregation function as a string.

Available aggregations are:

- `mean` : Computes the mean of the column
- `mean` : Computes the sum of the column
- `max` : Computes the maximum of the column
- `min` : Computes the minimum of the column
- `filter:value`: Filters the column by `value`.


[NOTE]
====
The order of the aggregations list is important.
====


== Custom layouts

By providing the `layout_modifiers` field, users can pass custom layout options for rendering the figures.
These options correspond to the accepted layout reference for Plotly: https://plotly.com/python/reference/layout/[Plotly layout reference]
It accepts a nested dictionnary just as Plotly does.

For example, we could customize a figure to have have its x-axis on a logscale.
[source,json]
----
"layout_modifiers":{
    "xaxis":{
        "type":"log"
    }
}
----


++++
<style>
details>.title::before, details>.title::after {
    visibility: hidden;
}
details>.content>.dynamic-py-result>.content>pre {
    max-height: 100%;
    padding: 0;
    margin:16px;
    background-color: white;
    line-height:0;
}
</style>
++++