= Additional Files

This field allows the export of custom files, as well as use case descriptions and logs. It is optional.

description_filepath [*str*] (Optional)::
    Filepath of a file to be used as benchmark description.
    This file will be copied to the same directory of the performance report, named description.adoc, after all ReFrame tests are completed (successfully or not).
    This file will automatically appear in the website for the current report, treated as an Antora partial.

parameterized_descriptions_filepath [*str*] (Optional)::
    Parameterized filepath (using either `{\{instance\}}` or `{{parameters.MY_PARAM.value}}`) of a file generated by a test.
    This file will be copied right after a test finishes (only if successful).
    The copied file will be located in a _partials_ directory, under the current exported report directory. It will be named after the tests hashcode.
    These files will automatically appear in the website, inside the parameter table of  the current report, and are treated as Antora partials.


custom_logs [*List[str]*] (Optional)::
    List of parameter depdendent filepaths of logs to be included in the website.

[CAUTION]
====
Currently, it is imposed for `description` and `parameterized_description` files to be in AsciiDoc format.
====

== Examples

Let's suppose that our benchmarked application produces an _information.adoc_ file each time it runs. And that we have a use case description named _description.adoc_. Also, let's assume that our app logs some information under _logs/log.INFO_ and under _logs/log.WARNING_ each time it runs.

If we have set our application to write its outputs under _/data/outputs/{\{instance\}}_. Then our `additional_files` field will look like this.

[source,json]
----
"additional_files":{
    "description_filepath":"/data/outputs/description.adoc",
    "parameterized_descriptions_filepath":"/data/outputs/{{instance}}/information.adoc",
    "custom_logs":[
        "/data/outputs/{{instance}}/logs/log.INFO",
        "/data/outputs/{{instance}}/logs/log.WARNING"
    ]
}
----

All these files will automatically appear on the website's report page.
