= Grid Node

The **Grid Node** is a layout node that can be used to structure content into a grid. Mainly used to arrange images, plots, or tables side by side in a visually appealing manner. Sub figures or sub plots can be created using this node, but numbering and labeling must be handled manually within the captions of the child nodes.

|===
|Field|Type|Description|Default Value

|`id`|string| *Optional.* Identifies the grid node within the report. Used for internal cross referencing |`null`
|`type`|string|Must be set to `"grid"`.|`"grid"`
|`caption`|string|*Optional.* A descriptive caption for the grid.|`null`
|`contents`|array of objects| A list of other (non-recursive) content nodes.|[]
|columns|int| Number of columns for the grid. Must be between 1 and 4.| 1
|gap|int| Must be beween 1 and 3| 2.
|justify| string("start","center","end")|horizontal alignment of the grid items.| "start"
|align| string("start","center","end")|vertical alignment of the grid items.| "start"
|===

[IMPORTANT]
Only non-nested types are allowed as children. This node's content CANNOT be of type `section` nor `grid`.

== Example

[source,json]
----
{
    "contents":[
        {
            "type":"grid",
            "columns":3,
            "gap":2,
            "align":"center",
            "justify":"center",
            "contents":[
                {"type":"image","src":"...","caption":"Image 1"}
                {"type":"image","src":"...","caption":"Image 2"}
                {"type":"image","src":"...","caption":"Image 3"}
            ]
        }
    ]
}
----