= feelpp.benchmarkign project

== Welcome to Feel++ Benchmarking

The _Feel++ benchmarking_ project provides a framework for automating, centralizing and organizing performance evaluation of scientific simulations on HPC systems.
This project, based on the https://reframe-hpc.readthedocs.io/en/stable/index.html[ReFrame-hpc framework], enables highly customized benchmarking using robust and comprehensive JSON configuration files that parametrize tests, validate executions and generate figures.
It also provides concrete CI/CD/CB pipelines to fully automate the benchmarking step of any application.

== How it works



== Getting started

=== Installation

. Clone the Repository
[source,cmd]
----
git clone https://github.com/feelpp/benchmarking.git
----

. Use a python virtual environment [Optional]
[source,cmd]
----
python3 -m venv .venv
source .venv/bin/activate
----

. Build the project
[source,cmd]
----
pip3 wheel --no-deps --wheel-dir dist .
----

. Install requirements

This will install necessary dependencies as well as the built project from the previous step.
[source,cmd]
----
python3 -m pip install -r requirements.txt
----

=== Quickstart

The framwork includes a sample C++/MPI application that can be used to get familiar with the framework's core concepts. It can be found under _tests/data/parallelSum.cpp_.

This Feel++ Benchmarking "Hello World" application will compute the sum of an array distributed across multiple MPI processes. Each process will compute a partial sum, and then it will be summed to get the total sum.

Additionally, the app will measure the time taken to perform the partial sum, and will save it under a _scalability.json_ file.

The executable is already provided as _tests/data/parallelSum_.

- Where configs are, (also reframe config).
- execute-benchmark



== Configuration guide

=== System configuration

=== Magic strings

=== Machine configuration

=== Benchmark configuration

=== Overview configuration

=== Plots configuration

== Benchmarking Workflow

== Interpreting Benchmarks

== CI/CD and Automation

== Versioning

== Advanced usage

== Examples