name: Preview Staging Website

on:
    pull_request:
        types:
            - labeled
            - opened
    push:
        branches:
            - '181-handle-report-deployment' #TODO: Remove (DEBUG)
jobs:
    preview-staging:
        runs-on: self-ubuntu-22.04
        name: Preview stage benchmarks
        if: contains(github.event.pull_request.labels.*.name,'new-benchmark')
        steps:
            -   uses: actions/checkout@v4
            -   name: Build wheel
                run: |
                    npm install
                    npx downdoc README.adoc
                    pip3 wheel --no-deps --wheel-dir dist .
                env:
                    CXX: clang++
            -   name: Create python environment
                run: |
                    python3 -m venv .venv
                    source .venv/bin/activate
                    pip3 install -r requirements.txt
            -   name: Download stage benchmarks
                run: |
                    source .venv/bin/activate
                    girder-download -gid 6752b5194c9ccbdde21a48b8 -o ./tmp/ -d
                env:
                    GIRDER_API_KEY: ${{secrets.GIRDER}}
            -   name: Merge Website Configs
                run: |
                    source .venv/bin/activate
                    merge-json-configs -fp ./tmp/**/website_config.json -o ./tmp/website_config.json -u
            -   name: Trigger Preview
                uses: netlify/actions/build@master
                env:
                    NETLIFY_CMD: "./netlify-stage-build.sh"
                    NETLIFY_DIR: public
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

